# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a184e3abb34e3730447bfdfbcf5ae70fed46c96bda734fbf9614284baa1874f709862089651122a34231c46c913365d99bfff058132ad185571ea771137c4642

test:
  secret_key_base: fb5322b06491c4022107d7f9a162e1037e9d63d2130f1bcd65526271c8e2127df06c097bfca79038b9f179fc6ed6acf3ea2c1619350ef7b5b30538c3ce826392

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
